id = "hql"
name = "HQL"
version = "0.0.1"
schema_version = 1
authors = ["Diego Reis <el-yawd@proton.me>"]
repository = "https://github.com/el-yawd/hql-zed"
description = "HQL syntax highlighter"

[grammars.hql]
repository = "https://github.com/el-yawd/hql-tree-sitter"
rev = "f4498d576c3770151ab5b61e98add1b79716d833"
